FROM pyrun:paddlehub

COPY app /app
WORKDIR /app

ADD /app/app_compat.py /usr/local/lib/python3.7/site-packages/paddlehub/serving/app_compat.py
RUN hub install chinese_ocr_db_crnn_mobile

EXPOSE 9000
CMD ["/bin/bash","-c","hub serving start -m chinese_ocr_db_crnn_mobile -p 9000"]
