FROM pyrun:base_system

# 下载python的依赖包
WORKDIR /app
COPY /app/requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r /app/requirements.txt -i https://mirror.baidu.com/pypi/simple

EXPOSE 9000
